Task/add actions - DO NOT MERGE
bosonprotocol/docs.bosonprotocol.io pull request #57
Opened 2021-12-09 10:56 UTC by Rhian

Add three separate workflows: build, deploy to staging and deploy to production.

- Build runs on every push and every PR
- Deploy to staging runs on merge to main
- Deploy to production is manual (after staging has been validated)

# Known issues

- Github secrets need to be added
-  Terraform needs to be checked

2022-01-18 12:21 UTC, radu-stefanache requested changes
In general, I would assume the action would:
1. Build and test
2. Run terraform just in case you have infra changes
3. Update the CDN content and create an invalidation (I believe this is missing)

2022-01-18 12:21 UTC, radu-stefanache commented on .github/workflows/deploy-production.yml
> +          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
This should be changed to `AWS_ACCESS_KEY_ID_PROD`

2022-01-18 12:21 UTC, radu-stefanache commented on .github/workflows/deploy-production.yml
> +          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
This should be changed to `AWS_SECRET_ACCESS_KEY_PROD`

2022-01-18 12:21 UTC, radu-stefanache commented on .github/workflows/deploy-production.yml
> +          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
This should be changed to `AWS_ACCESS_KEY_ID_PROD`

2022-01-18 12:21 UTC, radu-stefanache commented on .github/workflows/deploy-production.yml
> +          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
This should be changed to `AWS_SECRET_ACCESS_KEY_PROD`

2022-01-18 12:21 UTC, radu-stefanache commented on .github/workflows/build.yml
> +        run: bundle exec rake
I did not check the `Rakefile` but if this will also update the CDN content (and create an invalidation), given the current action `on` statement, it will update/invalidate the CDN distro on simple pull requests which is probably not what you want ?

2022-01-25 09:11 UTC, Rhian commented on .github/workflows/deploy-production.yml
> +          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
Fixed

2022-01-25 09:13 UTC, Rhian commented on .github/workflows/build.yml
> +        run: bundle exec rake
I've split the Rake tasks so that we have a `build_fix` task and a `build_deploy` task. The former builds, tests and fixes linting errors while the latter does these tasks plus updates/invalidates. So we'd use the `build_fix` task for PRs and the `build_deploy` for updates.

2022-01-25 11:07 UTC, radu-stefanache approved these changes
LGTM :+1:

2022-01-25 12:32 UTC, merged